name: "Terraform Destroy"

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Sammyvirtual-solution"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Laravel-with-Terraform-Github_Action"
  CONFIG_DIRECTORY: "./"

jobs:
    terraform:
        if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
        name: Destroy terraform workspace
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Upload Configuration
              uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
              id: destroy-upload
              with: 
                workspace: ${{ env.TF_WORKSPACE }}
                directory: ${{ env.CONFIG_DIRECTORY }}
            
            - name: terraform_destroy
              uses: dflook/terraform-destroy@v1
              id: first_try
              continue-on-error: true
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
                
            - name: Retry failed destroy
              uses: dflook/terraform-destroy@v1
              if: ${{ steps.first_try.outputs.failure-reason == 'destroy-failed' }}
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}
