name: "Terraform Destroy"

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Sammyvirtual-solution"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Laravel-with-Terraform-Github_Action"
  CONFIG_DIRECTORY: "./"

jobs:
    terraform:
        if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
        name: Destroy terraform workspace
        runs-on: ubuntu-latest
        permissions:
          contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Upload Configuration
              uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.4
              id: apply-upload
              with: 
                workspace: ${{ env.TF_WORKSPACE }}
                directory: ${{ env.CONFIG_DIRECTORY }}

            - name: Create Apply Run
              uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.4
              id: apply-run
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

            - name: terraform_destroy
              if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
              id: destroy
              run: |
                terraform init
                terraform plan -destroy -out=destroy.tfplan
                terraform apply destroy.tfplan
