name: "Terraform Destroy"

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "Sammyvirtual-solution"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Laravel-with-Terraform-Github_Action"
  CONFIG_DIRECTORY: "./"

jobs:
    destory_workspace:
        runs-on: ubuntu-latest
        name: Destroy terraform workspace
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: terraform_destroy
              uses: dflook/terraform-destroy@v1
              id: first_try
              continue-on-error: true
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                directory: ${{ env.CONFIG_DIRECTORY }}
                
            - name: Retry failed destroy
              uses: dflook/terraform-destroy@v1
              if: ${{ steps.first_try.outputs.failure-reason == 'destroy-failed' }}
              with:
                workspace: ${{ env.TF_WORKSPACE }}
                directory: ${{ env.CONFIG_DIRECTORY }}